remarkjs/remark-lint

doc/rules.md, lib/rules/meta.js, script/additional.json, script/build-rule-documentation.js
@wooorm Currently the TOC is with list style stars (`*`) but `mdas-toc` yields dashes (`-`) for me.
According to it's repo `dash` is the correct style.
Thus I haven't added the generator output here. Will do after clarification.
While pushing I thought about just creating empty `<rule-id>.js` files with nothing more than comments in it, so the auto-generation works.
Because for this approach here I'd also like a way to not store its texts inline.
=> Adds support for automatic doc generation for file-less rules

readme.md
Thanks!
- __docs__: fix typo in readme
=> docs: fix typo in readme

lib/index.js
Electron app runs on Node.js environment, so `isGlobal` should be `true`.  But Electron app has its own binary to execute.  Its `process.argv` will be `['/path/to/MyApp']`, not `['/path/to/node', '/path/to/entrypoint.js']`.  So we can't detect Electron app from `process.argv[1]`.
Instead, we can do that with existence of `process.versions.electron`.  It will not be `undefined` only in Electron environment.
This change will not break other environment because of just adding above check.
This fix will make remark-lint detect Electron environment as Node.js environment correctly.
- Build and linter passed
- All test passed
- Coverage 100%
- [Tried in my Electron app](https://github.com/rhysd/Shiba/blob/master/package.json#L39)
- Node.js 5.9.0
- Electron 0.37.2
- OS X 10.11.4
=> Support Electron environment

lib/rules/hard-break-spaces.js
Remove '\r' from the end of the contents if it exists
fixes #55
=> fix CRLF issue with hard-break-spaces

readme.md
see https://github.com/wooorm/remark/pull/217#issuecomment-267150813
=> Added remark-lint-appropriate-heading to plugins

readme.md
Now [ale](https://github.com/w0rp/ale) integrates remark-lint to check editing markdown documents on the fly with Vim :+1:
=> Doc: ale integrates remark-lint as Vim plugin

readme.md
Adding this package: https://github.com/vhf/remark-lint-heading-whitespace
=> Add `remark-lint-heading-whitespace` to plugins list

readme.md
I add remark integration for Sublime Text and Grunt.
grunt-remark [**poorly documented**](https://www.npmjs.com/package/grunt-remark), but successfully works for me with plugins, presets and configurations.
See my [**pull request**](https://github.com/j616/SublimeLinter-contrib-remark-lint/pull/1), it fixes error and add support for any plugin, preset and configuration.
Thanks.
=> Add Sublime and Grunt to list of integrations

readme.md
I've created a [jest-runner](https://jestjs.io/docs/en/configuration#runner-string) ([jest-runner-remark](https://github.com/keplersj/jest-runner-remark)) that checks Markdown files against remark, thought I'd share it here and hopefully in the Integrations list!
=> Add jest-runner-remark to integrations list

packages/remark-lint-ordered-list-marker-value/index.js, packages/remark-lint-ordered-list-marker-value/readme.md
Here's small patch that allow to use 0 as start value in ordered list for https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-ordered-list-marker-value rule.
Why is that need? Because lists like that should be valid:
```markdown
0. zero
1. one
2. two
3. three
```
but it's not with current implementation:
> Marker should be `2`, was `1`  ordered-list-marker-value  remark-lint
[Example](https://astexplorer.net/#/gist/aee4106f9fbb2bd58f7bd1af2cba13fb/f296549aebf441f0fac64885a0e4213571da40d7)
I'm working now on remark lint preset for Gatsby docs and faced with this issue here:
That's not a BREAKING CHANGE and tests seems okay
=> Updated validation to allow 0 as start value for ordered list

readme.md
This adds vscode-remark-lint to the list of integrations. 😃
=> Add `vscode-remark-lint` to the list of integrations

packages/remark-lint-maximum-line-length/index.js
https://spectrum.chat/unified/remark/excluding-frontmatter-from-remark-lint-rules~fbe35244-c33d-4f97-bf21-b15c196a52a3
=> maximum-line-length: ignore `yaml`, `toml`

packages/remark-lint-no-duplicate-headings-in-section/index.js, test.js
👋 First of all, sry for not opening an issue first – I was not sure if it's a bug or by design, then I wrote a test to verify my issue and then I was too curious about the codebase to resist tinkering with it :) 🤓 
---
**Current behavior:**
`remark-lint-no-duplicate-headings-in-section` doesn't detect duplicate headings when those headings are not sequentially incremented.
```
```
**Proposed behavior:** 
👀 but not sure if it should be like this by default, or with an option
Duplicate headings in sections should be detected even when they are not sequentially incremented.
Maybe better explained in the test.
=> no-duplicate-headings-in-section: fix missing warning on depth-jump

doc/rules.md, package.json, packages/remark-lint-strikethrough-marker/index.js, packages/remark-lint-strikethrough-marker/package.json, packages/remark-lint-strikethrough-marker/readme.md
I've used the emphasis linting example and implemented it pretty similar for the strikethrough rule.
I didn't get how the tests are generated/handled from the comments. There are 3 errors corresponding to the new package. 
How can I fix these?
=> Add `remark-lint-strikethrough-marker`

.github/workflows/main.yml
There's an apparent conflict between new versions of Node.js (? 17.5.0)/npm (? 8.4.1) and old versions of nvm-windows (? [1.1.7](https://github.com/dcodeIO/setup-node-nvm/blob/3bc09a3f6f58358a453eccc31a88b0c661cba9f9/install.ps1#L6)):
- https://github.com/remarkjs/remark-lint/runs/5239128363?check_suite_focus=true#step:4:4
- https://github.com/npm/cli/issues/4340#issuecomment-1035608510
I didn't get to the absolute bottom of it because https://github.com/dcodeIO/setup-node-nvm hasn't been updated in a while and describes itself as …
=> Fix Node in Actions on Windows

packages/unified-lint-rule/lib/index.js
Should this boolean branch be removed, along with this comment? https://github.com/remarkjs/remark-lint/commit/4a832b145ef9087e2619eb7b2144e02830130c11#diff-fecb2d96324cc527540b9781510b84d13095032247186df5ce672b22171c78dcL51-L52
Since https://github.com/unifiedjs/unified/pull/185 it's untested, as before https://github.com/unifiedjs/unified/pull/150.
=> Remove boolean fallback for ancient remark

packages/unified-lint-rule/index.d.ts, readme.md
Non-array arguments are a rule's options, not a severity.
Makes `remark().use(remarkLintUnorderedListMarkerStyle, 'off')` a type error, to match the runtime error:
```
1:1: Incorrect unordered list item marker style `off`: use either `'-'`, `'*'`, or `'+'`
```
=> Fix types of rule arguments

packages/unified-lint-rule/lib/index.js
What do you think of this cosmetic change to the `coerce()` function?
It's not an important change. As I see it the advantage is it eliminates the `// @ts-expect-error: it’s now a valid tuple.` exception, so the type checker confirms it actually returns a `SeverityTuple`.
I'm happy to make any stylistic changes you suggest!
=> Type-safe severity/options normalization

packages/remark-lint-no-undefined-references/index.js, packages/remark-lint-no-undefined-references/readme.md, test.js
I've added support for regex patterns in the `allow` option in the [`no-undefined-references`](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-undefined-references) rule.
Let me know what you think. :slightly_smiling_face:
Closes #296.
=> no-undefined-references: add support for regex as option

packages/remark-lint/index.js
=> Fix `this` type in TS 4.9

packages/remark-lint-maximum-line-length/index.js, packages/remark-lint-maximum-line-length/readme.md
Fixes: https://github.com/remarkjs/remark-lint/issues/318
Fixes maximum line length calculation bug in https://github.com/remarkjs/remark-lint/issues/318.
=> maximum-line-length: fix long links

readme.md
Hey everyone! While working on the project, I created three new plugins and I want to share them with the community and I hope my plugins will be useful. I have added links to them in readme.md.
These are three plugins:
- [remark-lint-check-toc](https://github.com/ilyatitovich/remark-lint-check-toc) - checks the correctness of the existing table of contents
- [remark-lint-code-block-split-list](https://github.com/ilyatitovich/remark-lint-code-block-split-list) - checks that code block inside list does not split the list
- …
=> Add three new rules to list of rules

packages/remark-lint-no-unused-definitions/package.json
Fixes #327, see this issue for more details.
=> `remark-lint-no-unused-definitions`: Switch `unist-util-visit` dependency to `unist-util-visit-parents`
